# International Football Data Analysis

This project analyzes historical international football matches using:

- Results Dataset
- Goalscorers Dataset
- Shootouts Dataset
- Former Country Names Dataset

Goal:
- Discover trends
- Analyze team performance
- Study goalscoring patterns
- Explore penalty shootouts

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")

In [2]:
results = pd.read_csv("data/results.csv")
goals = pd.read_csv("data/goalscorers.csv")
shootouts = pd.read_csv("data/shootouts.csv")
former = pd.read_csv("data/former_names.csv")

In [ ]:
results.head()
results.info()
results.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49437 entries, 0 to 49436
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49437 non-null  object
 1   home_team   49437 non-null  object
 2   away_team   49437 non-null  object
 3   home_score  49365 non-null  float64
 4   away_score  49365 non-null  float64
 5   tournament  49437 non-null  object
 6   city        49437 non-null  object
 7   country     49437 non-null  object
 8   neutral     49437 non-null  bool
dtypes: bool(1), float64(2), object(6)
memory usage: 3.1+ MB

         home_score    away_score
count  49365.000000  49365.000000
mean       1.757419      1.182032
std        1.774524      1.402391
min        0.000000      0.000000
25%        1.000000      0.000000
50%        1.000000      1.000000
75%        2.000000      2.000000
max       31.000000     21.000000

In [ ]:
results.head()
results.info()
results.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49437 entries, 0 to 49436
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49437 non-null  object
 1   home_team   49437 non-null  object
 2   away_team   49437 non-null  object
 3   home_score  49365 non-null  float64
 4   away_score  49365 non-null  float64
 5   tournament  49437 non-null  object
 6   city        49437 non-null  object
 7   country     49437 non-null  object
 8   neutral     49437 non-null  bool
dtypes: bool(1), float64(2), object(6)
memory usage: 3.1+ MB

         home_score    away_score
count  49365.000000  49365.000000
mean       1.757419      1.182032
std        1.774524      1.402391
min        0.000000      0.000000
25%        1.000000      0.000000
50%        1.000000      1.000000
75%        2.000000      2.000000
max       31.000000     21.000000

In [5]:
goals.head()

goals.info()

goals.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47601 entries, 0 to 47600
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       47601 non-null  object
 1   home_team  47601 non-null  object
 2   away_team  47601 non-null  object
 3   team       47601 non-null  object
 4   scorer     47553 non-null  object
 5   minute     47345 non-null  float64
 6   own_goal   47601 non-null  bool
 7   penalty    47601 non-null  bool
dtypes: bool(2), float64(1), object(5)
memory usage: 2.3+ MB

             minute
count  47345.000000
mean      50.047397
std       26.363283
min        1.000000
25%       28.000000
50%       51.000000
75%       73.000000
max      122.000000

In [6]:
shootouts.head()
shootouts.info()
shootouts.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 678 entries, 0 to 677
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           678 non-null    object
 1   home_team      678 non-null    object
 2   away_team      678 non-null    object
 3   winner         678 non-null    object
 4   first_shooter  248 non-null    object
dtypes: object(5)
memory usage: 26.6+ KB

              date     home_team away_team       winner first_shooter
count          678           678       678          678           248
unique         593           188       198          183            90
top     2024-03-26  South Africa     Egypt  South Korea      Colombia
freq             5            18        16           15            11

In [7]:
former.head()
former.info()
former.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   current     36 non-null     object
 1   former      36 non-null     object
 2   start_date  36 non-null     object
 3   end_date    36 non-null     object
dtypes: object(4)
memory usage: 1.3+ KB

         current   former  start_date    end_date
count         36       36          36          36
unique        28       36          36          36
top     DR Congo  Dahomey  1959-11-08  1975-11-30
freq           4        1           1           1

In [8]:
results.isnull().sum()
results.duplicated().sum()

np.int64(0)

In [9]:
results['date'] = pd.to_datetime(results['date'])

In [10]:
goals.isnull().sum()
goals.duplicated().sum()

np.int64(82)

In [11]:
goals['date'] = pd.to_datetime(results['date'])

In [12]:
shootouts.isnull().sum()
shootouts.duplicated().sum()

np.int64(0)

In [13]:
shootouts['date'] = pd.to_datetime(results['date'])

In [14]:
former.isnull().sum()
former.duplicated().sum()

np.int64(0)

In [15]:
former['date'] = pd.to_datetime(results['date'])